version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo-zesty
    environment:
      MONGO_INITDB_DATABASE: zesty
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo:
